project_name: lprobe

before:
  hooks:
    - go mod download

builds:
- env:
  - CGO_ENABLED=0
  ldflags: ["-w -s"]
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64

archives:
  - format: binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-snap"

changelog:
  use: github