project_name: lprobe

before:
  hooks:
    - go mod download

builds:
- env:
  - CGO_ENABLED=0
  ldflags: ["-w -s"]
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64

archives:
  - format: binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-snap"

changelog:
  use: github

dockers:
- image_templates: ["ghcr.io/fivexl/{{ .ProjectName }}:{{ .Version }}-amd64"]
  goos: linux
  goarch: amd64
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/fivexl/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/fivexl/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=Apache-2.0
- image_templates: ["ghcr.io/fivexl/{{ .ProjectName }}:{{ .Version }}-arm64v8"]
  goos: linux
  goarch: arm64
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/fivexl/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/fivexl/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=Apache-2.0
docker_manifests:
- name_template: ghcr.io/fivexl/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - ghcr.io/fivexl/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/fivexl/{{ .ProjectName }}:{{ .Version }}-arm64v8
- name_template: ghcr.io/fivexl/{{ .ProjectName }}:latest
  image_templates:
  - ghcr.io/fivexl/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/fivexl/{{ .ProjectName }}:{{ .Version }}-arm64v8
