name: CI

on:
  push:
    tags: [ v* ]
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19
      id: go      

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Run test.sh
      run: |
        scripts/test.sh

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    needs: [ tests ]
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3.2.0
      with:
        version: v1.50.1

    - name: Prepare a snapshot release
      if: "!startsWith(github.ref, 'refs/tags/v')"
      uses: goreleaser/goreleaser-action@v3
      with:
        version: latest
        args: release --clean --snapshot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_CLI_EXPERIMENTAL: "enabled"

    - name: Release a new version
      if: startsWith(github.ref, 'refs/tags/v')
      uses: goreleaser/goreleaser-action@v4
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_CLI_EXPERIMENTAL: "enabled"

